### ISSUE TITLE
priceLine

### ISSUE THREAD

**Issue by steveumg** [NotCoffee418/TradingView.Blazor#10]
how difficult would it be to add the Priceline option 

`const priceLine = {
		price: 980,
		color: '#be1238',
		lineWidth: 2,
		lineStyle: LightweightCharts.LineStyle.Dotted,
		axisLabelVisible: true,
		title: 'P/L: 500',
	};`

**Comment by NotCoffee418** [comment]
It's a bit tricky without breaking stuff or doing a proper overhaul but I'll make it happen.
If this library becomes more popular, i'll do a full overhaul so it can be expanded properly without hacky code.
