### ISSUE TITLE
backgroundColor has been deprecated.

### ISSUE THREAD

**Issue by cyberyaga** [NotCoffee418/TradingView.Blazor#13]
Hello... I edited this post, to point out some changes in the TradingView lightweight chart API.

It seems that the:
_layout / backgroundColor_
property has been deprecated. And it's not even present in v4.0 of the API.
[https://tradingview.github.io/lightweight-charts/docs/3.8/api/interfaces/LayoutOptions](url)

This makes the component always show up with a background of white. 
![image](https://user-images.githubusercontent.com/30553591/222038259-188cd16f-6fad-4743-a9af-1ee0de67a839.png)

Thanks again :)

**Comment by NotCoffee418** [comment]
fixed in v1.1.1
