### ISSUE TITLE
Time and price not displaying anymore

### ISSUE THREAD

**Issue by cheriansk** [NotCoffee418/TradingView.Blazor#14]
![image]
Not showing time and price

**Comment by jonathanAnnandale** [comment]
Hi guys
In ChartHelperInterop.js there is a method called createChart. Within there, the layout section has an incorrect property.
Change "backgroundColor" to "background".

Thanks for the great project :-)

**Comment by NotCoffee418** [comment]
Hey, gonna close this since I can't see the issue.
@jonathanAnnandale Fixing background color now
