### ISSUE TITLE
Have you ever tried to implement markets

### ISSUE THREAD

**Issue by Acruval** [NotCoffee418/TradingView.Blazor#2]
Hi not Coffee
Thanks for your code
I have adapted you component to Blazor Server 3.1 sucessfully
But I was not be able to implement the markers.
https://www.tradingview.com/lightweight-charts/
https://jsfiddle.net/TradingView/nd80cx1a
I intrepid to copy paste examples of markets and I got nothing
https://github.com/tradingview/lightweight-charts/blob/master/docs/series-basics.md
Have you ever tried this?

In theory is only add marker to an existing serie like for example 

candleSeries..setMarkers([
    {
        time: '2019-04-09',
        position: 'aboveBar',
        color: 'black',
        shape: 'arrowDown',
    },
    {
        time: '2019-05-31',
        position: 'belowBar',
        color: 'red',
        shape: 'arrowUp',
        id: 'id3',
    },
    {
        time: '2019-05-31',
        position: 'belowBar',
        color: 'orange',
        shape: 'arrowUp',
        id: 'id4',
        text: 'example',
        size: 2,
    },
]);

**Comment by NotCoffee418** [comment]
Hey, i dont think i actually finished implementing the markers since i don't need them right away and i didnt expect anyone to actually use this.
I'll have a look somewhere this week and see whats going on.

**Comment by NotCoffee418** [comment]
@Acruval Markers will now work correctly. Fixed in 7b1fd3816e8b78894487a6e0164e856baeee68b9

**Comment by Acruval** [comment]
Hi Not Coffe.
As I said I tried to implement this functionality based on the js library
but I could not. Well, I was using net 3.1, but I think the problem was
js.
I will check your code later in detail and see what I am doing with height
width.
I understand you do this in your free time so THANK YOU very much.

Ps
You should have something like a sponsor or donations

Thank  you very much
Antonio

**Comment by NotCoffee418** [comment]
@Acruval it was an issue with my implementation of it.
Markers would break when the width is less than 0, which happens when you make the size responsive. This is now prevented.

In any case, i expect it to work when you update the nuget package to 1.0.2 without needing additional changes to your code.

And thanks for the kind words!
