### ISSUE TITLE
How to update chart data?

### ISSUE THREAD

**Issue by boffman** [NotCoffee418/TradingView.Blazor#3]
Hi, thanks for a nice module!
I'm wondering if it's possible to redraw the chart with new data somehow (like, switch instrument to view)?

Right now if I update the data and run "await myChart.LoadChartAsync(data, options);" again, I get a new chart below the last one.

**Comment by NotCoffee418** [comment]
Give me a few hours, i'' see if i can implement a more effective way to append and update data.

**Comment by NotCoffee418** [comment]
You should be able to refresh an existing chart now by calling `await myChart.UpdateChartAsync(updatedChartData);`.
You need to pass the new or updated chart data, but options are will be retained from the initial call to LoadChartAsync().

**Comment by boffman** [comment]
It worked fine - thanks alot!
