### ISSUE TITLE
Any way to specify time scale on the chart?

### ISSUE THREAD

**Issue by cyberyaga** [NotCoffee418/TradingView.Blazor#7]
First of all... Thank you for this component... It's a simple component that serves a good purpose.

I am using it in my web page. But I am running into the issue of my candles being one sided on the chart when it loads.

Here is an example:
![image](https://user-images.githubusercontent.com/30553591/179370288-63cfcd31-1f49-4807-a482-f65271d9bcc6.png)

I know that in the TradingView API reference there is a way to provide the time scale of the chart. Or even to resize the chart with the candle data that it has.

But this is not available on your component. Would that be something that it could be made available?

I would try to take a swing at it, but I'm horrible with JS and the way Blazor interacts with it.

Also, another thing... I've noticed that when the price data is very small (over 3 decimal places) the price doesn't reflect in the price scale. Very small numbers are common in markets like crypto. Is that also something that can be addressed.

Thanks again for the work you've done.

**Comment by NotCoffee418** [comment]
It's been a while since I touched this library but I'll take some time and see what i can do for you.

**Comment by NotCoffee418** [comment]
Both issues have been addressed. You can upgrade to [v1.0.5](https://www.nuget.org/packages/TradingView.Blazor/1.0.5) to take advantage of them.

To change the decimal precision in the price chart you can set the new chart option `RightPriceScaleDecimalPrecision` to the amount of decimals you want.

The empty space will automatically no longer occur, as the chart will auto fit immidiately after creation.

Additionally, you can pass in your own arguments directly into the js library with the following new properties in ChartOptions:
```csharp
// -- Custom definitions
/// <summary>
/// Options defined here will be added to the chart when calling createChart()
/// Example usage:
/// options.CustomChartDefinitions["height"] = 500;
/// </summary>
public Dictionary<string, dynamic> CustomChartDefinitions { get; set; } = new();

/// <summary>
/// Options defined here will be added to the chart when calling addCandlestickSeries()
/// Example usage:
/// options.CustomCandleSeriesDefinitions["borderVisible"] = false;
/// </summary>
public Dictionary<string, dynamic> CustomCandleSeriesDefinitions { get; set; } = new();

/// <summary>
/// Options defined here will be added to the chart when calling addHistogramSeries()
/// Example usage:
/// options.CustomVolumeSeriesDefinitions["color"] = "#26a69a";
/// </summary>
public Dictionary<string, dynamic> CustomVolumeSeriesDefinitions { get; set; } = new();
```

**Comment by cyberyaga** [comment]
> Both issues have been addressed. You can upgrade to [v1.0.5](https://www.nuget.org/packages/TradingView.Blazor/1.0.5) to take advantage of them.
> 
> To change the decimal precision in the price chart you can set the new chart option `RightPriceScaleDecimalPrecision` to the amount of decimals you want.
> 
> The empty space will automatically no longer occur, as the chart will auto fit immidiately after creation.
> 
> Additionally, you can pass in your own arguments directly into the js library with the following new properties in ChartOptions:
> 
> ```cs
> // -- Custom definitions
> /// <summary>
> /// Options defined here will be added to the chart when calling createChart()
> /// Example usage:
> /// options.CustomChartDefinitions["height"] = 500;
> /// </summary>
> public Dictionary<string, dynamic> CustomChartDefinitions { get; set; } = new();
> 
> /// <summary>
> /// Options defined here will be added to the chart when calling addCandlestickSeries()
> /// Example usage:
> /// options.CustomCandleSeriesDefinitions["borderVisible"] = false;
> /// </summary>
> public Dictionary<string, dynamic> CustomCandleSeriesDefinitions { get; set; } = new();
> 
> /// <summary>
> /// Options defined here will be added to the chart when calling addHistogramSeries()
> /// Example usage:
> /// options.CustomVolumeSeriesDefinitions["color"] = "#26a69a";
> /// </summary>
> public Dictionary<string, dynamic> CustomVolumeSeriesDefinitions { get; set; } = new();
> ```

Wow... Thanks a million... Really appreciate this.

**Comment by cyberyaga** [comment]
FYI... I just updated the package:

And I soon as I ran it, the chart doesn't show and I got this on the browser:
![image](https://user-images.githubusercontent.com/30553591/179680492-061b09cb-6bc3-412b-9730-6ff3dc7291a5.png)

Here is what the debugger in VSCode tells me:
`Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'btGu_4s3wHzMlZ-5Z_r1_wKO2viKgsB6DXFzFNfKGxo'.

Microsoft.JSInterop.JSException: error loading dynamically imported module

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at TradingView.Blazor.ChartHelperInterop.LoadChart(ElementReference eleRef, ChartData data, ChartOptions options)
   at TradingView.Blazor.TradingViewChart.LoadChartAsync(ChartData data, ChartOptions options)
   at UI.Pages.Bot.Portfolio.LoadTradeViewChart(List`1 orders) in /home/cyberyaga/Projects/ChigueteBotWeb/UI/Pages/Bot/Portfolio.razor:line 416
   at UI.Pages.Bot.Portfolio.onRowClick(Account a) in /home/cyberyaga/Projects/ChigueteBotWeb/UI/Pages/Bot/Portfolio.razor:line 378
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`
